### ISSUE TITLE
the results are not displayed or saved,

### ISSUE THREAD

**Issue by cyh-123** [Gradiant/pyodi#162]
When I run `pyodi ground-truth ../instances_train2017.json` according to the tutorial, the results are not displayed or saved, and the code does not report errors. The following are the results:
```
2021-08-27 21:57:18.223 | INFO     | pyodi.core.utils:coco_ground_truth_to_df:38 - Loading Ground Truth File
2021-08-27 21:57:18.302 | INFO     | pyodi.core.utils:coco_ground_truth_to_df:48 - Converting COCO Ground Truth to pd.DataFrame
2021-08-27 21:57:18.418 | INFO     | pyodi.plots.common:plot_scatter_with_histograms:61 - Plotting Scatter with Histograms
2021-08-27 21:57:18.735 | INFO     | pyodi.plots.common:plot_scatter_with_histograms:61 - Plotting Scatter with Histograms

```

**Comment by cyh-123** [comment]
Thank you very much, I have solved this problem, i changed "output: Optional[str] = None" to my own path in "pyodi/pyodi/plots/common.py"

**Comment by mmeendez8** [comment]
Note you can also  pass the argument output:

`pyodi ground-truth ../instances_train2017.json --output [your-output-folder-path]`

**Comment by cyh-123** [comment]
ok, thank you very much, I recommend you can modify your readme is more better.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gradiant/pyodi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月28日(星期六) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gradiant/pyodi] the results are not displayed or saved, (#162)





 
Note you can also  pass the argument output:
 
pyodi ground-truth ../instances_train2017.json --output [your-output-folder-path]
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
