### ISSUE TITLE
Image width and height swapped due to not respecting EXIF information

### ISSUE THREAD

**Issue by tracek** [Gradiant/pyodi#182]
When loading an image for painting annotations, Pillow is used to load the image. Trouble is, the [Image.open](ImageOps.exif_transpose(im)) function does not take EXIF information into the consideration, so the width and height are swapped in the end result.

Consider applying:
```
ImageOps.exif_transpose(image)
```

Perhaps as an option? I could submit a PR.

**Comment by jorgenusan** [comment]
Hello!

It may be fine as an option. You can open a PR whenever you want to implement it :)

**Comment by tracek** [comment]
Hey - and done: https://github.com/Gradiant/pyodi/pull/185 

BTW, nice work!
